	

	
	

	<a href="#" title="Close lightbox" id="lbox-bttn-close" class="ibutton"><i class="icon-remove-sign icon-large"></i></a>

	<a href="#" title="Enter fullscreen" id="lbox-bttn-fs" class="ibutton"><i class="icon-fullscreen icon-large"></i></a>

	<a href="#" title="Exit fullscreen" id="lbox-bttn-ns" class="ibutton"><i class="icon-resize-small icon-large"></i></a>	<a href="#" id="lbox-bttn-play" class="ibutton">
	<i class="icon-play icon-large"></i>
	</a>
	
	<a href="#" id="lbox-bttn-pause" class="ibutton">
	<i class="icon-pause icon-large"></i>
	</a>

	<div id="lnav" class="tnav">
	<a href="/koken/content/3/in_album/1/lightbox" lightbox="true" class="ibutton">
	<i class="icon-angle-left"></i>
	</a>
	</div>

	<div id="main">

	<div id="spinner"></div>

	<div id="content">

	<script>
	window.albumId = 1;
	</script>
	
	<script>
	window.aspect = 1.5;
	window.contentId = 4;
	window.videoFile = false;
	window.presets = [
	{
	url: 'http://was-chani-mache.ch/koken/storage/cache/000/004/DSCF1922,tiny.jpg?1362052330',
	width: 60,
	height: 40	},	{
	url: 'http://was-chani-mache.ch/koken/storage/cache/000/004/DSCF1922,small.jpg?1362052330',
	width: 100,
	height: 67	},	{
	url: 'http://was-chani-mache.ch/koken/storage/cache/000/004/DSCF1922,medium.jpg?1362052330',
	width: 480,
	height: 320	},	{
	url: 'http://was-chani-mache.ch/koken/storage/cache/000/004/DSCF1922,medium_large.jpg?1362052330',
	width: 800,
	height: 533	},	{
	url: 'http://was-chani-mache.ch/koken/storage/cache/000/004/DSCF1922,large.jpg?1362052330',
	width: 1024,
	height: 683	},	{
	url: 'http://was-chani-mache.ch/koken/storage/cache/000/004/DSCF1922,xlarge.jpg?1362052330',
	width: 1500,
	height: 1000	},	{
	url: 'http://was-chani-mache.ch/koken/storage/cache/000/004/DSCF1922,huge.jpg?1362052330',
	width: 1500,
	height: 1000	}	];
	</script>

	<div class="caption" style="display:none">
	<strong></strong>
	&nbsp;&nbsp;
	</div>
	</div>

	</div>

	<div id="rnav" class="tnav">
	<a href="/koken/content/5/in_album/1/lightbox" lightbox="true" class="ibutton">
	<i class="icon-angle-right"></i>
	</a>
	</div>

	<footer>
	<a href="/" title="Back to site">Boris Baldinger</a>
	&nbsp;&nbsp;
	4 of 5 from the album <a href="/koken/albums/1">Februar 2013</a>	&nbsp;&nbsp;
	<a id="btn-toggle" href="#" title="Show caption">Show caption</a>
	</footer>

	
	<script>update();</script>
<title>DSCF1922.jpg - Boris Baldinger</title>